### PR TITLE
Custom config locations to search

### PR DESCRIPTION
**Pull request by drudv**
It will allow to customize config locations in case user wants to place its global config, for instance, in his/her home folder or in other places, where prettier can't find them by default.

### CODE REVIEW

**Comment by drudv** [comment]
@danreeves Could you please take look at this PR? Are you fine with this `configLocations` setting? Thanks

**Comment by danreeves** [comment]
~Seems good. One thing is that prettier supports a bunch of config file names other than `.prettierrc`, documented here: https://prettier.io/docs/en/configuration.html~

~Should we look for those by default too? Or should we look for nothing by default and have users set their own `configLocations`?~

Ignore me, I just realised you're not setting anything by default 👍

**Review by danreeves — APPROVED** [review]
Tested it out and it works fine 👍

**Comment by drudv** [comment]
@danreeves cool, thanks!

**Pull request merged**
